CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AuditLog" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text,
    "Action" text,
    "Details" text,
    "IpAddress" text,
    "TenantId" uuid,
    "Timestamp" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuditLog" PRIMARY KEY ("Id")
);

CREATE TABLE "PendingEmails" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Recipient" text NOT NULL,
    "Subject" text NOT NULL,
    "Body" text NOT NULL,
    "IsSent" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "RetryCount" integer NOT NULL,
    "Type" integer NOT NULL,
    CONSTRAINT "PK_PendingEmails" PRIMARY KEY ("Id")
);

CREATE TABLE "PendingFiles" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "FileName" text NOT NULL,
    "FolderName" text NOT NULL,
    "Type" integer NOT NULL,
    "Status" integer NOT NULL,
    "RetryCount" integer NOT NULL,
    "ErrorMessage" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "FinishedAt" timestamp with time zone,
    CONSTRAINT "PK_PendingFiles" PRIMARY KEY ("Id")
);

CREATE TABLE results (
    "Id" uuid NOT NULL,
    "CandidateId" uuid NOT NULL,
    "TotalVotes" integer NOT NULL,
    CONSTRAINT "PK_results" PRIMARY KEY ("Id")
);

CREATE TABLE "States" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "Name" character varying(100) NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_States" PRIMARY KEY ("Id")
);

CREATE TABLE "SupportTickets" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Email" text NOT NULL,
    "Subject" text NOT NULL,
    "Message" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsResolved" boolean NOT NULL,
    "IpAdidress" text,
    "TenantId" uuid,
    CONSTRAINT "PK_SupportTickets" PRIMARY KEY ("Id")
);

CREATE TABLE "Tenants" (
    "Id" uuid NOT NULL,
    "OrganizationName" text NOT NULL,
    "TenantCategory" integer NOT NULL,
    "Slug" text NOT NULL,
    "SubscriptionPlan" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsApproved" boolean NOT NULL,
    "IsActive" boolean NOT NULL,
    "MaxAllowedElections" integer NOT NULL,
    "ProfilePicture" text,
    CONSTRAINT "PK_Tenants" PRIMARY KEY ("Id")
);

CREATE TABLE "voterRegistrations" (
    "Id" uuid NOT NULL,
    "UserID" uuid NOT NULL,
    "ElectionId" uuid NOT NULL,
    "hasVoted" boolean NOT NULL,
    CONSTRAINT "PK_voterRegistrations" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Lgas" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "Name" character varying(100) NOT NULL,
    "StateId" uuid NOT NULL,
    "DeletedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Lgas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Lgas_States_StateId" FOREIGN KEY ("StateId") REFERENCES "States" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ElectionEvents" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "Title" text,
    "Description" text,
    "ElectionYear" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "Category" integer NOT NULL,
    "TenantId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "ImageUrl" text,
    "DeletedAt" timestamp with time zone,
    CONSTRAINT "PK_ElectionEvents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ElectionEvents_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id")
);

CREATE TABLE "Party" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "Name" character varying(150) NOT NULL,
    "Description" text,
    "LogoUrl" text,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "TenantId" uuid,
    CONSTRAINT "PK_Party" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Party_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id")
);

CREATE TABLE "Users" (
    "Id" text NOT NULL,
    "FullName" character varying(200) NOT NULL,
    "Address" text,
    "DateOfBirth" timestamp with time zone,
    "VoterRegistrationID" text,
    "VoteCastTime" timestamp with time zone,
    "OfficialStaffId" text NOT NULL,
    "DepartmentorAgency" text,
    "StateId" uuid,
    "HasVoted" boolean NOT NULL,
    "isVoter" boolean NOT NULL,
    "profileImage" text,
    "TenantId" uuid,
    "IsApproved" boolean NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_States_StateId" FOREIGN KEY ("StateId") REFERENCES "States" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Users_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id")
);

CREATE TABLE "candidateInvitations" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "TenantId" uuid,
    "ElectionEventId" uuid NOT NULL,
    "CandidateEmail" text,
    "Token" text NOT NULL,
    "IsUsed" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_candidateInvitations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_candidateInvitations_ElectionEvents_ElectionEventId" FOREIGN KEY ("ElectionEventId") REFERENCES "ElectionEvents" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_candidateInvitations_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id")
);

CREATE TABLE "ElectionCustomFields" (
    "Id" uuid NOT NULL,
    "TenantId" uuid,
    "ElectionEventId" uuid,
    "FieldName" text NOT NULL,
    "FieldType" text NOT NULL,
    "FormCategory" integer NOT NULL,
    "CustomChoicesCsv" text,
    "IsRequired" boolean NOT NULL,
    CONSTRAINT "PK_ElectionCustomFields" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ElectionCustomFields_ElectionEvents_ElectionEventId" FOREIGN KEY ("ElectionEventId") REFERENCES "ElectionEvents" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ElectionCustomFields_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id")
);

CREATE TABLE "Position" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "Name" character varying(100) NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone NOT NULL,
    "TenantId" uuid,
    "ElectionEventId" uuid,
    CONSTRAINT "PK_Position" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Position_ElectionEvents_ElectionEventId" FOREIGN KEY ("ElectionEventId") REFERENCES "ElectionEvents" ("Id"),
    CONSTRAINT "FK_Position_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id")
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Candidate" (
    "Id" uuid NOT NULL DEFAULT (gen_random_uuid()),
    "CandidateID" text,
    "Name" character varying(200) NOT NULL,
    "Slug" character varying(150) NOT NULL,
    "Manifesto" text,
    "CandidateImg" text,
    "isDeleted" boolean NOT NULL,
    "DeletedAt" timestamp with time zone,
    "isApproved" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ElectionEventId" uuid,
    "StateId" uuid,
    "UserId" text,
    "PartyId" uuid,
    "PositionId" uuid,
    "LgaId" uuid,
    "TenantId" uuid,
    "StatesId" uuid,
    CONSTRAINT "PK_Candidate" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Candidate_ElectionEvents_ElectionEventId" FOREIGN KEY ("ElectionEventId") REFERENCES "ElectionEvents" ("Id"),
    CONSTRAINT "FK_Candidate_Lgas_LgaId" FOREIGN KEY ("LgaId") REFERENCES "Lgas" ("Id"),
    CONSTRAINT "FK_Candidate_Party_PartyId" FOREIGN KEY ("PartyId") REFERENCES "Party" ("Id"),
    CONSTRAINT "FK_Candidate_Position_PositionId" FOREIGN KEY ("PositionId") REFERENCES "Position" ("Id"),
    CONSTRAINT "FK_Candidate_States_StateId" FOREIGN KEY ("StateId") REFERENCES "States" ("Id"),
    CONSTRAINT "FK_Candidate_States_StatesId" FOREIGN KEY ("StatesId") REFERENCES "States" ("Id"),
    CONSTRAINT "FK_Candidate_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id"),
    CONSTRAINT "FK_Candidate_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
);

CREATE TABLE "CandidateCustomValues" (
    "Id" uuid NOT NULL,
    "CandidateId" uuid NOT NULL,
    "FieldId" uuid NOT NULL,
    "Value" text NOT NULL,
    "TenantId" uuid,
    CONSTRAINT "PK_CandidateCustomValues" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CandidateCustomValues_Candidate_CandidateId" FOREIGN KEY ("CandidateId") REFERENCES "Candidate" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CandidateCustomValues_ElectionCustomFields_FieldId" FOREIGN KEY ("FieldId") REFERENCES "ElectionCustomFields" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_CandidateCustomValues_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id")
);

CREATE TABLE "CandidateGalleries" (
    "Id" uuid NOT NULL,
    "CandidateId" uuid NOT NULL,
    "ImageUrl" text NOT NULL,
    "UploadedAt" timestamp with time zone NOT NULL,
    "TenantId" uuid,
    CONSTRAINT "PK_CandidateGalleries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CandidateGalleries_Candidate_CandidateId" FOREIGN KEY ("CandidateId") REFERENCES "Candidate" ("Id"),
    CONSTRAINT "FK_CandidateGalleries_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id")
);

CREATE TABLE "Votes" (
    "Id" uuid NOT NULL,
    "VoterId" text,
    "CandidateId" uuid,
    "StateId" uuid,
    "ElectionId" uuid,
    "PositionId" uuid,
    "CastAt" timestamp with time zone,
    "VotedAt" timestamp with time zone NOT NULL,
    "TenantId" uuid,
    "IsConfirmed" boolean NOT NULL,
    "HasVoted" boolean NOT NULL,
    "ConfirmationCode" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "IsPenalized" boolean NOT NULL,
    CONSTRAINT "PK_Votes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Votes_Candidate_CandidateId" FOREIGN KEY ("CandidateId") REFERENCES "Candidate" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Votes_ElectionEvents_ElectionId" FOREIGN KEY ("ElectionId") REFERENCES "ElectionEvents" ("Id"),
    CONSTRAINT "FK_Votes_Position_PositionId" FOREIGN KEY ("PositionId") REFERENCES "Position" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Votes_States_StateId" FOREIGN KEY ("StateId") REFERENCES "States" ("Id"),
    CONSTRAINT "FK_Votes_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id"),
    CONSTRAINT "FK_Votes_Users_VoterId" FOREIGN KEY ("VoterId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "IX_Candidate_ElectionEventId" ON "Candidate" ("ElectionEventId");

CREATE INDEX "IX_Candidate_LgaId" ON "Candidate" ("LgaId");

CREATE INDEX "IX_Candidate_PartyId" ON "Candidate" ("PartyId");

CREATE INDEX "IX_Candidate_PositionId" ON "Candidate" ("PositionId");

CREATE UNIQUE INDEX "IX_Candidate_Slug" ON "Candidate" ("Slug");

CREATE INDEX "IX_Candidate_StateId" ON "Candidate" ("StateId");

CREATE INDEX "IX_Candidate_StatesId" ON "Candidate" ("StatesId");

CREATE INDEX "IX_Candidate_TenantId" ON "Candidate" ("TenantId");

CREATE INDEX "IX_Candidate_UserId" ON "Candidate" ("UserId");

CREATE INDEX "IX_CandidateCustomValues_CandidateId" ON "CandidateCustomValues" ("CandidateId");

CREATE INDEX "IX_CandidateCustomValues_FieldId" ON "CandidateCustomValues" ("FieldId");

CREATE INDEX "IX_CandidateCustomValues_TenantId" ON "CandidateCustomValues" ("TenantId");

CREATE INDEX "IX_CandidateGalleries_CandidateId" ON "CandidateGalleries" ("CandidateId");

CREATE INDEX "IX_CandidateGalleries_TenantId" ON "CandidateGalleries" ("TenantId");

CREATE INDEX "IX_candidateInvitations_ElectionEventId" ON "candidateInvitations" ("ElectionEventId");

CREATE INDEX "IX_candidateInvitations_TenantId" ON "candidateInvitations" ("TenantId");

CREATE INDEX "IX_ElectionCustomFields_ElectionEventId" ON "ElectionCustomFields" ("ElectionEventId");

CREATE INDEX "IX_ElectionCustomFields_TenantId" ON "ElectionCustomFields" ("TenantId");

CREATE INDEX "IX_ElectionEvents_TenantId" ON "ElectionEvents" ("TenantId");

CREATE UNIQUE INDEX "IX_ElectionEvents_Title" ON "ElectionEvents" ("Title");

CREATE INDEX "IX_Lgas_StateId" ON "Lgas" ("StateId");

CREATE INDEX "IX_Party_TenantId" ON "Party" ("TenantId");

CREATE INDEX "IX_Position_ElectionEventId" ON "Position" ("ElectionEventId");

CREATE INDEX "IX_Position_TenantId" ON "Position" ("TenantId");

CREATE INDEX "EmailIndex" ON "Users" ("NormalizedEmail");

CREATE INDEX "IX_Users_StateId" ON "Users" ("StateId");

CREATE INDEX "IX_Users_TenantId" ON "Users" ("TenantId");

CREATE UNIQUE INDEX "UserNameIndex" ON "Users" ("NormalizedUserName");

CREATE INDEX "IX_Votes_CandidateId" ON "Votes" ("CandidateId");

CREATE INDEX "IX_Votes_ElectionId" ON "Votes" ("ElectionId");

CREATE INDEX "IX_Votes_PositionId" ON "Votes" ("PositionId");

CREATE INDEX "IX_Votes_StateId" ON "Votes" ("StateId");

CREATE INDEX "IX_Votes_TenantId" ON "Votes" ("TenantId");

CREATE INDEX "IX_Votes_VoterId" ON "Votes" ("VoterId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260905113057_InitialPostgreSQLMigration', '9.0.12');

COMMIT;

