<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>07d8e847-f29f-41c2-a1b5-6bf410b1c737</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AppleAuth.NET" Version="1.0.8" />
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
    <PackageReference Include="Hashids.net" Version="1.7.0" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.12" />
    <PackageReference Include="Microsoft.Build" Version="17.14.28" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.14.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="4.14.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.14.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Features" Version="4.14.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" Version="4.14.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.18" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.12" />
    <PackageReference Include="MimeKit" Version="4.17.0" />
    <PackageReference Include="Npgsql" Version="9.0.5" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.2" />
    <PackageReference Include="Resend" Version="0.16.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="Slugify.Core" Version="5.1.1" />
    <PackageReference Include="StackExchange.Redis" Version="3.0.17" />
    <PackageReference Include="Supabase" Version="1.5.0" />
    <PackageReference Include="Tailwind.Extensions.AspNetCore" Version="1.1.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="tests\" />
    <Folder Include="wwwroot\Candidate_Profiles\" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\STICKZZOFFICIAL\source\repos\OnlineVotingApplication\OnlineVotingApplication\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Views\Shared\_Layout.cshtml.css" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\STICKZZOFFICIAL\source\repos\OnlineVotingApplication\OnlineVotingApplication\.editorconfig" />
  </ItemGroup>

</Project>
