namespace OnlineVotingApplication.Enums
{
    public enum FileType
    {

        //// --- Bulk Data Import Assets (Processed line-by-line via StreamReader) ---
        //VoterManifest = 1,        // CSV/Excel bulk upload of eligible voters
        //CandidateList = 2,        // CSV/JSON bulk upload of candidates running for office
        //PollingStationList = 3,   // CSV upload of physical voting locations and centers

        //// --- Graphic & Visual Assets (Saved to disk, paths saved to Database) ---
        //CandidateProfileImage = 4, // JPG/PNG photographs of candidates for the ballot screen
        //PartyLogo = 5,            // SVG/PNG political party branding logos
        //VoterIdSignature = 6,     // Scanned images/PDFs of signatures or government IDs for verification

        //// --- Data Export & Audit Assets (Generated by the server, saved to disk) ---
        //ElectionResultsReport = 7, // Generated PDFs or Excel sheets containing final vote counts
        //AuditTrailLog = 8,        // Cryptographic voting log files for independent election verification
        //BallotPaperTemplate = 9   // PDF printouts of the digital
        Image, Video
    }
}
